### ISSUE TITLE
Подключение к БД

### ISSUE THREAD

**Issue by IlnazMmm** [RedColdHearted/Flask-ServiceLogix#1]
Привет, хотел запустить проект, но чет ошибки вылезли с подключением к БД. 
Запускал команды 
`flask db init`
`flask db migrate`
`flask db upgrade`
Но все равно таблицы не создаются

<details><summary>errors</summary>

![image](https://github.com/RedColdHearted/Flask-ServiceLogix/assets/100714975/41dcdb4e-def1-4673-8643-e2c6d4a660f5)
</details>

<details><summary>config</summary>

![image](https://github.com/RedColdHearted/Flask-ServiceLogix/assets/100714975/daad793a-c16c-425a-8355-8f68fe9a840a)
</details>

<details><summary>.env</summary>

![image](https://github.com/RedColdHearted/Flask-ServiceLogix/assets/100714975/6b4454fa-198c-429d-9282-ef89d70e809d)
</details>

**Comment by RedColdHearted** [comment]
если ты хочешь использовать Postgresql, тебе необходимо указать в .env у DATABASE_URL подключение к твоей базе данных: postgresql://пользователь:пароль@адрес/имя_базы_данных, если тебе хватает sqlite, то достаточно закомментировать эту строчку в .env

**Comment by IlnazMmm** [comment]
Хммм, в .env я url к базе оставил, подключение то есть, но таблицы он туда почему-то не может мигрировать

**Comment by IlnazMmm** [comment]
c sqlite такая ж проблема при миграции таблицы не создаются.

![image](https://github.com/RedColdHearted/Flask-ServiceLogix/assets/100714975/3c76e8ad-7429-4a27-bf2a-683a112cc747)

Файл с миграцией [fdbdd5bbe141_.txt](https://github.com/user-attachments/files/15885948/fdbdd5bbe141_.txt)

**Comment by RedColdHearted** [comment]
попробуй добавить в начале url postgresql+psycopg2 и указать localhost вместо db

**Comment by RedColdHearted** [comment]
db вместо localhost необходимо указывать при docker-compose иначе подключение внутри контейнера будет по tcp/ip

**Comment by IlnazMmm** [comment]
Я изначально так и писал, но все равно ошибки при миграции. Так ж и в sqlite не проходит миграция

**Comment by IlnazMmm** [comment]
Я конечно могу руками в postgre создать таблицы, но все равно странно почему не проходит миграция

**Comment by IlnazMmm** [comment]
windows

**Comment by RedColdHearted** [comment]
попробуй закомментировать url в env, удалить папку с миграциями и мигрировать заново, если будет ошибка кинь скрин

**Comment by RedColdHearted** [comment]
python3 -m venv venv

venv/Scripts/activate

pip install -r requirements.txt


сделай виртуальное окружение, скорее всего из за этого

**Comment by IlnazMmm** [comment]
Да, окужение я не делал

**Comment by IlnazMmm** [comment]
все гуд
