### ISSUE TITLE
Ошибка при редактировании заявки на ремонт

### ISSUE THREAD

**Issue by IlnazMmm** [RedColdHearted/Flask-ServiceLogix#2]
Шаги воспроизведения:
1. Нажать на `Создать заявку`
2. Заполнить заявку
3. Нажать на `Отправить`
4. В гриде выбрать новую заявку и нажать на `Изменить`
5. Выбрать мастера и заполнить необходимые поля
6. Нажать на `Сохранить`

Ошибка из-за того что в поле `Мастер` принимает объект **RepairRequest** а не тип str.
И после сохранения изменения заявка уходит в историю, но по логике должна остаться в заявках (Если статус не равно *COMPLETED*)

Я исправил все, могу запушить, посмотришь.

**Comment by RedColdHearted** [comment]
давай, тебя в контрибьютеры закинуть?

**Comment by IlnazMmm** [comment]
go

**Comment by RedColdHearted** [comment]
запуш в dev

**Comment by RedColdHearted** [comment]
а потом pull request сделай

**Comment by RedColdHearted** [comment]
или свою ветку сделай

**Comment by maximSytd** [comment]
попробуй гит пул с мейна сделать и за тестить, вроде я закинул в мейн ветку изменения

**Comment by IlnazMmm** [comment]
У меня конфиг на тесты не настроен пока что

**Comment by maximSytd** [comment]
всмысле? python -m unittest discover -s tests
