### ISSUE TITLE
Ошибка 404 при редактировании заявки, которые отфильтровались после поска по номеру телефона.

### ISSUE THREAD

**Issue by IlnazMmm** [RedColdHearted/Flask-ServiceLogix#4]
Шаги воспроизведения.
1. Зайти во вкладку `Заявки`
2. Нажать на `Поиск по телефону`
3. Ввести существующий номер телефона в БД
4. Нажать на `Поиск` (Выходят все записи по заданному номеру)
5. Нажать на изменить.

Ошибка выходит из-за того, что все записи после редактирования уходят в **историю**, а через поиск телефона у нас имеется доступ опять к редактированию той заявки, которая по сути уже завершена и находится в **истории**. 

Так как теперь только записи cо статусом **COMPLETED** после [мерджа](https://github.com/RedColdHearted/Flask-ServiceLogix/commit/e2ae79db3ce3eb2f07d0e05e4dd0cf2756d51a99) уходят в **историю**. Есть смысл в записях, отфильтрованных после поиска по номеру телефона, оставить кнопки **Подробнее** и **Изменить** только для заявок, у которых статус не **COMPLETED**. А к заявкам со статусом **COMPLETED** добавить только кнопку **Подробнее**.

И еще когда вы ищем по номеру телефона, идет поиск по любым совпадениям. Например есть заявка с номером - **23** (Что некорректно, номер должен быть не меньше и не больше 11 цифр), он находит все номера с таким совпадением. Т.е и номера 2424**23**34234, 1111**23**, и.т.д.

**Comment by IlnazMmm** [comment]
Запушу в ветку dev

**Comment by maximSytd** [comment]
принял

**Comment by maximSytd** [comment]
мне кажется есть смысл выводить все заявки и просто помечать выполненные

**Comment by IlnazMmm** [comment]
Выводятся все заявки. Просто у выполненных заявок не будет доступа к редактированию

**Comment by IlnazMmm** [comment]
Вот как будет выглядеть. (Верстку только подправить если)
![image](https://github.com/RedColdHearted/Flask-ServiceLogix/assets/100714975/4d58f497-2936-481f-81ae-e390aa60984a)

**Comment by maximSytd** [comment]
так норм вроде, только мне кажется валидатор для формы лишний

**Comment by IlnazMmm** [comment]
В валидаторе я поменял всего длинну записи в поле ввода номера телефона

**Comment by maximSytd** [comment]
ты забыл сделать так чтобы статус заявки менялся на complete, а так при выполнении меняется поле is_active

**Comment by maximSytd** [comment]
ща закомичу

**Comment by IlnazMmm** [comment]
> ты забыл сделать так чтобы статус заявки менялся на complete, а так при выполнении меняется поле is_active

А да, cогласен. Заявка в истории не уходит после редактирования

**Comment by maximSytd** [comment]
вообще криво как то получается, мне кажется надо избавиться от is_active

**Comment by maximSytd** [comment]
поработай над этим, поменяй модель, вью и шаблоны если тебе не лень

**Comment by IlnazMmm** [comment]
Хорошо, как время будет посмотрю
